version: "3.1"
services:
    db:
      container_name: 'rshop_mysql'
      image: mysql:5.7
      volumes:
        - ${DB_FILES}
      restart: always
      command: --sql_mode=""
      environment:
        MYSQL_ROOT_PASSWORD: ${DB_PASS}
        MYSQL_DATABASE: ${DB_DATABASE} 
        MYSQL_USER: ${DB_ROOT}
        MYSQL_PASSWORD: ${DB_PASS}
      ports:
       - ${DB_PORT}:3306

    p56:
      container_name: 'rshop_php56'
      depends_on:
        - db
      image: php:5.6
      build:
       context: .
       dockerfile: ./php56/Dockerfile
      links:
       - db
      volumes:
       - ${PHP56_FILES}
       - ./php56/php.ini:/usr/local/etc/php/conf.d/php.ini
      environment:
        DB_HOST: db:${DB_PORT}
        DB_PASSWORD: ${DB_PASS}
      ports:
       - ${PHP56_PORT}:80

    p71:
      container_name: 'rshop_php71'
      depends_on:
        - db
      restart: always
      image: php:7.1
      build:
       context: .
       dockerfile: ./php7/Dockerfile
      links:
       - db
       - memcached:memcached
       - elasticsearch:elasticsearch
      volumes:
       - ${PHP71_FILES}
       - ./php7/php.ini:/usr/local/etc/php/conf.d/php.ini
       - ./php7/virtualhost.conf:/etc/apache2/sites-available/virtualhost-php71.conf
      environment:
        DB_HOST: db:${DB_PORT}
        DB_PASSWORD: ${DB_PASS}
      ports:
       - ${PHP71_PORT}:80

    pma:
      container_name: 'rshop_phpmyadmin'
      depends_on:
        - db
      restart: always
      image: phpmyadmin/phpmyadmin
      ports:
        - "${PHPMY_PORT}:80"
      volumes:
       - ./phpmyadmin:/sessions

    memcached:
        container_name: 'rshop_memcached'
        image: memcached
        restart: always
        ports:
          - "${MEM_PORT}:11211"

    elasticsearch:
      container_name: 'rshop_elasticsearch'
      image: docker.elastic.co/elasticsearch/elasticsearch:6.2.2
      restart: always
      ports:
        - "${ELASTIC_PORT1}:9200"
        - "${ELASTIC_PORT2}:9300"

volumes:
   rshop-sync:
     external: true